import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"
import { OrganizationSwitcher } from "@/components/organization-switcher"

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <div className="flex min-h-screen flex-col bg-zinc-50">
            {/* Topbar */}
            {session && (
              <header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b bg-zinc-900 px-6 text-white shadow-sm">
                <div className="flex items-center gap-4">
                  <h1 className="text-xl font-bold tracking-tight">Esmerion IT</h1>
                  <OrganizationSwitcher />
                </div>
                <div className="flex items-center gap-4 text-sm">
                  <span>{session.user?.email}</span>
                </div>
              </header>
            )}

            <div className="flex flex-1">
              {/* Sidebar */}
              {session && (
                <aside className="w-64 border-r bg-white p-4 hidden md:block">
                  <nav className="space-y-2">
                    <div className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-4">Modules</div>
                    <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-900 hover:bg-zinc-100">Dashboard</a>
                    <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100">Finance & Receipts</a>
                    <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100">Tendering</a>
                    <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100">Design & Web</a>
                    <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100">Editorial & Publishing</a>
                    
                    {/* Superadmin Menu */}
                    {(session.user as any)?.isSystemSuperadmin && (
                      <>
                        <div className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mt-8 mb-4">Superadmin</div>
                        <a href="#" className="block rounded-md px-3 py-2 text-sm font-medium text-zinc-600 hover:bg-zinc-100">System Settings</a>
                      </>
                    )}
                  </nav>
                </aside>
              )}

              {/* Main Content */}
              <main className="flex-1 p-6">
                {children}
              </main>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
